// Copyright (C) 2011-2014 by Maximilian Hönig

#ifndef GUI_H
#define GUI_H

#include <irrlicht.h>

// Namespace Editor
namespace Editor
{
	// GUI class
	class CGUI
	{
	public:
		struct EGuiId
		{
			enum Enum
			{
				// Windows
				WINDOW_RANDOMCAVE = 0x10000,
				WINDOW_CAVE,
				WINDOW_OBJECTPLACEMENT,
				WINDOW_RANDOMOBJECTS,
				WINDOW_GAMEPLAY,
				WINDOW_DESCRIPTION,

				FILEOPENDIALOG_SAVE,
				FILEOPENDIALOG_LOAD,

				// Toolbar
				BUTTON_SAVE,
				BUTTON_LOAD,
				BUTTON_RANDOMCAVE,
				BUTTON_CAVE,
				BUTTON_OBJECTPLACEMENT,
				BUTTON_RANDOMOBJECTS,
				BUTTON_GAMEPLAY,
				BUTTON_DESCRIPTION,
		
				// Random Cave
				EDITBOX_ITERATION_RANDOM,

				EDITBOX_ANGLEYAW_MIN,
				EDITBOX_ANGLEYAW_MAX,
				EDITBOX_ANGLEYAW_DIGITS,

				EDITBOX_ANGLEPITCH_MIN,
				EDITBOX_ANGLEPITCH_MAX,
				EDITBOX_ANGLEPITCH_DIGITS,

				EDITBOX_ANGLEROLL_MIN,
				EDITBOX_ANGLEROLL_MAX,
				EDITBOX_ANGLEROLL_DIGITS,

				EDITBOX_RADIUSSTART_MIN,
				EDITBOX_RADIUSSTART_MAX,
				EDITBOX_RADIUSSTART_DIGITS,

				EDITBOX_STARTSTRING_ALLOWED_SYMBOLS,
				EDITBOX_STARTSTRING_MINLENGTH,
				EDITBOX_STARTSTRING_MAXLENGTH,

				EDITBOX_RULE_ALLOWED_SYMBOLS,
				EDITBOX_RULE_MINLENGTH,
				EDITBOX_RULE_MAXLENGTH,

				// Cave
				EDITBOX_COLOR_CAVE_R,
				EDITBOX_COLOR_CAVE_G,
				EDITBOX_COLOR_CAVE_B,

				EDITBOX_ITERATION,

				EDITBOX_ANGLEYAW_VALUE,
				EDITBOX_ANGLEPITCH_VALUE,
				EDITBOX_ANGLEROLL_VALUE,
				EDITBOX_RADIUSSTART_VALUE,
				EDITBOX_STARTSTRING_VALUE,

				EDITBOX_RULE_SYMBOL,
				EDITBOX_RULE_REPLACEMENT,
		
				BUTTON_RULE_ADD,
				BUTTON_RULE_DELETEALL,

				CHECKBOX_COLOR_CAVE_MULTICOLOR,
				CHECKBOX_EROSION,
				CHECKBOX_FILTERING,

				LISTBOX_RULES,

				// Object Placement
				EDITBOX_START_ROTATION_X,
				EDITBOX_START_ROTATION_Y,
				EDITBOX_START_ROTATION_Z,

				TEXTBOX_PLACED_START,
				TEXTBOX_PLACED_BOSS01,
				TEXTBOX_PLACED_BOSS02,
				TEXTBOX_PLACED_BOSS03,
				TEXTBOX_PLACED_BOSS04,
				TEXTBOX_PLACED_BOSS05,
				TEXTBOX_PLACED_BOSS06,

				BUTTON_APPLY_START,
				BUTTON_DELETE_START,
				BUTTON_DELETE_BOSS01,
				BUTTON_DELETE_BOSS02,
				BUTTON_DELETE_BOSS03,
				BUTTON_DELETE_BOSS04,
				BUTTON_DELETE_BOSS05,
				BUTTON_DELETE_BOSS06,

				// Random Objects
				EDITBOX_FACTOR_SHIP_RED,
				EDITBOX_FACTOR_SHIP_GREEN,
				EDITBOX_FACTOR_SHIP_BLUE,
				EDITBOX_FACTOR_SHIP_YELLOW,
				EDITBOX_FACTOR_SHIP_TEAL,
				EDITBOX_FACTOR_SHIP_PURPLE,
				EDITBOX_FACTOR_NO_SHIP,

				EDITBOX_ADDITIONAL_DISTANCE_SHIPS,
				EDITBOX_ADDITIONAL_DISTANCE_BOSSES,
				EDITBOX_ADDITIONAL_DISTANCE_START,

				// Gameplay
				EDITBOX_MONSTER_HITPOINTS,
				EDITBOX_BOSSMONSTER_HITPOINTS,
				EDITBOX_MONSTER_FIRETIME,
				EDITBOX_BOSSMONSTER_FIRETIME,
				EDITBOX_MONSTER_DAMAGE,

				// Description
				EDITBOX_DESCRIPTION_INTRO,
				EDITBOX_DESCRIPTION_EXTRO
			};
		};

	public:
		CGUI(irr::gui::IGUIEnvironment* guiEnvironment_);

		void CreateFileLoadDialog();
		void CreateFileSaveDialog();
		void CreateMenue();
		void CreateWindow_RandomCave();
		void CreateWindow_Cave();
		void CreateWindow_ObjectPlacement();
		void CreateWindow_RandomObjects();
		void CreateWindow_Gameplay();
		void CreateWindow_Description();

	private:
		// GUI Environment
		irr::gui::IGUIEnvironment* GUIEnvironment;

	};
	
} // END NAMESPACE DunGen

#endif